version: "3.9"
services:
  app:
    build:
      context: .
      target: dev
    container_name: tetris-app
    env_file:
      - .env
    ports:
      - "80:${APP_PORT}"
    volumes:
      - .:/app
